### ISSUE TITLE
Build Errors in PR101

### ISSUE THREAD

**Issue by xsscx** [InternationalColorConsortium/DemoIccMAX#102]
# [PR101](https://github.com/InternationalColorConsortium/DemoIccMAX/pull/101)

*November 22, 2024*

## Summary

PR101 results in [build errors](https://github.com/xsscx/PatchIccMAX/actions/runs/11976514433/job/33392359010) on the master branch. 

## Compile Errors
1. The type `CIccXformNDLut` is undefined in multiple locations.
2. Function `CIccApplyNDLutXform` has mismatched declarations and definitions.
3. Dependencies (e.g., `IccCmmConfig.cpp`) are removed in later commits.

### Step 1: Clone and Build
```bash
git clone https://github.com/InternationalColorConsortium/DemoIccMAX.git
cd DemoIccMAX/Build/
cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer -Wall" -Wno-dev Cmake/
make -j$(nproc) 2>&1 | grep 'error:'
```
**Result**: Build Errors

Errors include:
```plaintext
/home/xss/tmp/f464b41/DemoIccMAX/IccProfLib/IccCmm.h:1287:23: error: unknown type name 'CIccXformNDLut' (x12 occurrences)
```

### Step 2: Revert Commit [4dddd3](https://github.com/InternationalColorConsortium/DemoIccMAX/commit/f464b41bcfa87f40a4ffc67018801df4b74dddd3)
```bash
git revert --no-edit f464b41bcfa87f40a4ffc67018801df4b74dddd3
cd Build/
cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer -Wall" -Wno-dev Cmake/
make -j$(nproc) 2>&1 | grep 'error:'
```
**Result**: Build Errors

### Step 3: Revert Commits [9373786](https://github.com/InternationalColorConsortium/DemoIccMAX/commit/0f8bc1a0371f1cd26fbe642a0a5a22afe9373786) & [06ac1cc6](https://github.com/InternationalColorConsortium/DemoIccMAX/commit/b90ac3933da99179df26351c39d8d9d706ac1cc6)
```bash
git revert --no-edit -m 1 0f8bc1a0371f1cd26fbe642a0a5a22afe9373786
git revert --no-edit b90ac3933da99179df26351c39d8d9d706ac1cc6
cd Build/
cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer -Wall" -Wno-dev Cmake/
make -j$(nproc) 2>&1 | grep 'error:'
```
**Result**: Build Pass

### Verify Working Binaries
```bash
[2024-11-22 12:27:24 ~/tmp/f464b41/DemoIccMAX/Build]% Tools/IccFromXml/iccFromXml
IccFromXml built with IccProfLib Version 2.2.3, IccLibXML Version 2.2.3

Usage: IccFromXml xml_file saved_profile_file {-noid -v{=[relax_ng_schema_file - optional]}}

[2024-11-22 12:27:26 ~/tmp/f464b41/DemoIccMAX/Build]% Tools/IccToXml/iccToXml
IccToXml built with IccProfLib Version 2.2.3, IccLibXML Version 2.2.3

Usage: IccToXml src_icc_profile dest_xml_file
```
**Result**: Working Binaries

## Proposed
1. Revert Affected Commits
2. Accept [PR94](https://github.com/InternationalColorConsortium/DemoIccMAX/pull/94)

**Comment by maxderhak** [comment]
I was not seeing the compile error with my builds in VS2019.  I've moved the declaration of the apply object so that it comes after the xform object.
