### ISSUE TITLE
problem with compiling

### ISSUE THREAD

**Issue by wisdomk** [InternationalColorConsortium/DemoIccMAX#39]
since two days I am trying to compile the project with no success unfortunately.
I have followed whatever instructions were mentioned on the home page of the project for Windows OS (e.g. setting up all the necessary system variables LIBXML2, LIBTIFF...etc.) and yet it doesn't work!

I needed however actually to include the libraries explicitly in all the projects in visual studio solution and still it doesn't work.

Clearer instructions would be appreciated on how to make it runs.

**Comment by maxderhak** [comment]
I believe that @xsscx has addressed this now.
