### ISSUE TITLE
CLI tools do not report underlying IccProfLib version

### ISSUE THREAD

**Issue by petervwyatt** [InternationalColorConsortium/DemoIccMAX#42]
It would be extremely handy if all the CLI tools reported the version of the underlying IccProfLib as otherwise there is no known way to identify versioning information across multiple instances or from log files. Compile dates are obviously unreliable.

wxProfileDump already has the equivalent in the Help | About dialog.

The simplistic way is adding 2 lines of code to each CLI main program:
```
#include "IccProfLibVer.h"
...
printf("Built with IccProfLib version " ICCPROFLIBVER "\n");
```

Or you may prefer to implement as a method.
If you let me know your preference I am happy to make said changes... or you can do.

**Comment by maxderhak** [comment]
This has long since been added.  Closing issue for now.
