### ISSUE TITLE
A/B input/output confusion.

### ISSUE THREAD

**Issue by bungeman** [InternationalColorConsortium/DemoIccMAX#61]
While attempting to use `iccToXml` and `iccFromXml` to create a profile for "A CMYK (four channel)" to "B Lab (three channel)" the tool segfaulted. The issue is a confusion about properly keeping track of which of A and B are the input and the output. The "AtoB" and "BtoA" types do this fairly well, but the "Lut8" and "Lut16" types currently appear to always assume B is the input. This kinda works in a somewhat confusing way, but only when A and B have the same number of channels.

By creating a hack like https://github.com/bungeman/DemoIccMAX/commit/a963b3bc9bca7af2b91ef24841eba895e7a288c2 (originally against sample-icc and iccxml-code because that's what I found first) I am able to create and round trip a simple CMYK profile like [cmyk2x2.zip](https://github.com/InternationalColorConsortium/DemoIccMAX/files/14315587/cmyk2x2.zip) (zipped since I cannot attach a bare icc file here). Since this change isn't very clean at the moment I've decided to open this as an issue instead of as a pull request. Note that the messy part of this change is around informing the Lut classes of their direction, the changes to the classes to output correctly when they have the proper direction set seems to be correct.

**Comment by maxderhak** [comment]
The challenge with this suggestion is that it violates the ICC.1 specification.  I agree that there is not parity between AtoB and BtoA tag usage of lut8 and lut16.  That is the reason that the lutAtoB and lutBtoA tag types were created and introduces in the V4 specification.  If you want parity use the newer tags.  The order and meaning of the parts of the lut8 and lut16 are fixed.  Your changes are likely to not operate well with any CMM that conforms to the specification.
