### ISSUE TITLE
make error IccCmm.h:1246:37: error: expected ‘)’ before ‘*’ token

### ISSUE THREAD

**Issue by audioclassify** [InternationalColorConsortium/DemoIccMAX#82]
System:

`Ubuntu 22,04.4, AMD_64`

Commands:

```
gh repo clone InternationalColorConsortium/DemoIccMAX
cd ~/DemoIccMAX
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$HOME/.local ../Build/Cmake
make help
make
```

Output from make:

```
[  0%] Building CXX object IccProfLib/CMakeFiles/IccProfLib2.dir/home/ott/DemoIccMAX/IccProfLib/IccApplyBPC.cpp.o
In file included from /home/ott/DemoIccMAX/IccProfLib/IccApplyBPC.h:74,
                 from /home/ott/DemoIccMAX/IccProfLib/IccApplyBPC.cpp:71:
/home/ott/DemoIccMAX/IccProfLib/IccCmm.h:1246:37: error: expected ‘)’ before ‘*’ token
 1246 |   CIccApplyNDLutXform(CIccXformNDLut* pXform, CIccApplyCLUT* pApply);
      |                      ~              ^
      |                                     )
make[2]: *** [IccProfLib/CMakeFiles/IccProfLib2.dir/build.make:76: IccProfLib/CMakeFiles/IccProfLib2.dir/home/ott/DemoIccMAX/IccProfLib/IccApplyBPC.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:381: IccProfLib/CMakeFiles/IccProfLib2.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by xsscx** [comment]
Hello @audioclassify

Thank you for the confirmation with Host `Ubuntu 22,04.4, AMD_64`. [Issue 77](https://github.com/InternationalColorConsortium/DemoIccMAX/issues/77) noted these errors too. The workaround  is to Compile using PR https://github.com/InternationalColorConsortium/DemoIccMAX/pull/66
Commit [f891074a0f1c9d61a3dfa53749265f8c14ed4ee6](https://github.com/InternationalColorConsortium/DemoIccMAX/tree/f891074a0f1c9d61a3dfa53749265f8c14ed4ee6).

### PR 66 Reproduction
```
cd /tmp
wget https://github.com/InternationalColorConsortium/DemoIccMAX/archive/f891074a0f1c9d61a3dfa53749265f8c14ed4ee6.zip
unzip f891074a0f1c9d61a3dfa53749265f8c14ed4ee6.zip
cd DemoIccMAX-f891074a0f1c9d61a3dfa53749265f8c14ed4ee6/Build
cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer -Wall" -Wno-dev  Cmake
make -j$(nproc) 2>&1 | grep 'error:'
```
Result: Passing

If I can provide any additional info, or if there are any issues Compiling from Commit [f891074a0f1c9d61a3dfa53749265f8c14ed4ee6](https://github.com/InternationalColorConsortium/DemoIccMAX/tree/f891074a0f1c9d61a3dfa53749265f8c14ed4ee6) please update the issue.

**Comment by audioclassify** [comment]
Thank you for your quick reply. The code compiled without errors.

I created an output folder `~/DemoIccMAXresults` that sits next to the code folder `~/DemoIccMAX`.

The iccToXml command was tested with:

```
~/DemoIccMAX/build/Tools/IccToXml/iccToXml \
~/DemoIccMAX/Testing/CalcTest/calcUnderStack_sq.icc \
~/DemoIccMAXresults/iccToXmlTest0.xml
```

The output file contains well formed XML.

This issue is closed.
