### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by TahomaSoft** [InternationalColorConsortium/DemoIccMAX#86]
gcc --version
gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0

In file included from /home/eeck/Build/DemoICCMax/DemoIccMAX/IccProfLib/IccTag.h:90,
                 from /home/eeck/Build/DemoICCMax/DemoIccMAX/IccProfLib/IccCmm.h:77,
                 from /home/eeck/Build/DemoICCMax/DemoIccMAX/IccProfLib/IccApplyBPC.h:74,
                 from /home/eeck/Build/DemoICCMax/DemoIccMAX/IccProfLib/IccApplyBPC.cpp:71:
/home/erikbeck/Build/DemoICCMax/DemoIccMAX/IccProfLib/IccTagMPE.h:171:25: warning: ‘virtual CIccApplyMpe* CIccMultiProcessElement::GetNewApply(CIccApplyTagMpe*)’ was hidden [-Woverloaded-virtual=]
  171 |   virtual CIccApplyMpe* GetNewApply(CIccApplyTagMpe *pApplyTag);
      |                         ^~~~~~~~~~~
/home/eeck/Build/DemoICCMax/DemoIccMAX/IccProfLib/IccTagMPE.h:255:25: note:   by ‘virtual CIccApplyMpe* CIccMpeUnknown::GetNewApply()’
  255 |   virtual CIccApplyMpe *GetNewApply() { return NULL; }
      |                         ^~~~~~~~~~~
/home/eeck/Build/DemoICCMax/DemoIccMAX/IccProfLib/IccCmm.h:1246:37: error: expected ‘)’ before ‘*’ token
 1246 |   CIccApplyNDLutXform(CIccXformNDLut* pXform, CIccApplyCLUT* pApply);
      |                      ~              ^
      |                                     )

**Comment by TahomaSoft** [comment]
Thank you! Those directions pretty much worked; I needed to add a 'cd Build' statement and it cranked right along.

Erik

**Comment by TahomaSoft** [comment]
However, when I install and try to run the just-built binaries, I get the following errors:
./iccTiffDump: error while loading shared libraries: libIccProfLib2.so.2: cannot open shared object file: No such file or directory
 
 ./iccToXml 
./iccToXml: error while loading shared libraries: libIccXML2.so.2: cannot open shared object file: No such file or directory

Those shared libraries don't seem to be built using the recipe provided above.

Thanks,

Erik

**Comment by xsscx** [comment]
Hello @TahomaSoft 

Thank you for pointing out my CopyPasta error for the Build Instructions. My bad.

Good to hear you got a good compile.

You also identify a good point.. I should build static binaries so the lib loads don't bail out if not found in path.

I'll build the binaries on bare metal, re-check and update.

**Comment by xsscx** [comment]
Hello @TahomaSoft 

Thank you again for providing valuable feedback with respect to the Ubuntu Binaries and my needing to properly document the reproduction steps to download and run the package without friction.

My instructions always **try** provide CopyPasta to Success without friction, so I appreciate the feedback. 

My Ubuntu Package lacked proper instructions to download and install the binaries. I have updated the Instructions on that Download Page and provided same below.

The summary for installing and running the Ubuntu Binaries was to **export LD_LIBRARY_PATH=$(pwd)/lib:$LD_LIBRARY_PATH** and **chmod +x bin/**. I have tested the following CopyPasta on Bare Metal and WSL with Success.

Example
```
wget https://github.com/xsscx/PatchIccMAX/releases/download/ubuntu-x86_64/DemoIccMAX-ubuntu-commit-dc78afcfe9e8cf0dd027e8dd30e21bebf101ffaa-x86_64.zip
unzip DemoIccMAX-ubuntu-commit-dc78afcfe9e8cf0dd027e8dd30e21bebf101ffaa-x86_64.zip
cd DemoIccMAX-ubuntu-commit-dc78afcfe9e8cf0dd027e8dd30e21bebf101ffaa-x86_64
export LD_LIBRARY_PATH=$(pwd)/lib:$LD_LIBRARY_PATH
chmod +x bin/
bin/iccDumpProfile
```

Expectd Output
```
Usage: iccDumpProfile {-v} {int} profile {tagId to dump/"ALL"}
Built with IccProfLib version 2.2.3
```

If I can provide any additional information or help to compile etc, please update the Issue.

**Comment by xsscx** [comment]
## Windows Binaries
```
curl -L -o demoiccmax-windows11-x86_64.zip https://github.com/xsscx/PatchIccMAX/releases/download/windows-x86_64/demoiccmax-windows11-x86_64.zip
tar -xf demoiccmax-windows11-x86_64.zip
cd .\demoiccmax-windows11-x86_64\
```

## Test
```
.\iccApplyNamedCmm.exe
.\iccApplyProfiles.exe
.\iccDumpProfile.exe
.\IccFromXml.exe
.\IccToXml.exe
.\iccRoundTrip.exe
.\iccSpecSepToTiff.exe
.\iccTiffDump.exe
```

**Comment by xsscx** [comment]
Closing this Issue given PR https://github.com/InternationalColorConsortium/DemoIccMAX/pull/87

**Comment by TahomaSoft** [comment]
Thank you!  I'll test it again.
